title: Shuai Feng
url: "https://fengshuai0210.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "CV"
   link: "about"
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
 - name: "Contact"
   link: "contact"
