title: Shuai Feng
institute: Hebei Normal University
email: sfeng[at]hebtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  <b>Occam-Einstein Razor</b> <p>Physics should be as simple as possible, but not simpler.</p>
url: "https://fengshuai0210.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

#footer: yes
#footer_url: ""
#footer_text: "路漫漫其修远兮，吾将上下而求索"

facebook_id: fengshuai0210

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
# - name: "CV"
#   link: "about"
 - name: "Research"
   link: "/research"
 - name: "Teaching"
   link: "/teaching"
# - name: "Contact"
#   link: "contact"
# - name: "Links"
#   link: "/links"
