title: Shuai Feng
institute: Hebei Normal University </br>Shijiazhuang, Hebei Province, China 
email: sfeng[at]hebtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  <b>路漫漫其修远兮，吾将上下而求索</b> <p>——屈原</p>
url: "https://fengshuai0210.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
#footer_url: ""
footer_text: "路漫漫其修远兮，吾将上下而求索"

facebook_id: fengshuai0210

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
# - name: "CV"
#   link: "/cv"
# - name: "Group"
#   link: "/group"
 - name: "Research"
   link: "/research"
 - name: "Teaching"
   link: "/teaching"
# - name: "Contact"
#   link: "contact"
# - name: "Links"
#   link: "/links"
